# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/ for more details

version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
        name: Install Docker client
        command: apk add docker-cli
      # - run:
      #   name: "Build TEST docker image"
      #   command: docker-compose build --build-arg NODE_ENV=test api
      # - run:
      #   name: "Run lint && test && && build"
      #   command: mkdir -m 777 build && docker-compose run api sh -c 'yarn lint && yarn test --forceExit && yarn build'
      # - run:
      #   name: "Build PRODUCTION docker image"
      #   command: docker build --tag api:latest --tag api:$CIRCLE_BUILD_NUM --build-arg NODE_ENV=production .
